run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - gocritic
    - gosec
    - revive

linters-settings:
  revive:
    severity: warning

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
