version: 1

linters:
  enable:
    - gocritic
    - gosec
    - revive

linters-settings:
  revive:
    severity: warning

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

  exclude-use-default: false

  exclude:
    - "comment on exported"
    - "should have a package comment"

  exclude-dirs:
    - third_party
    - builtin
    - examples

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
